// <auto-generated />
using System;
using AIATC.Domain.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AIATC.Domain.Migrations
{
    [DbContext(typeof(AircraftControlDbContext))]
    partial class AircraftControlDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AIATC.Domain.Models.Users.AuthToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("ip_address");

                    b.Property<bool>("IsRevoked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_revoked");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("token");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("type");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("user_agent");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_auth_tokens_expires_at");

                    b.HasIndex("IsRevoked")
                        .HasDatabaseName("ix_auth_tokens_is_revoked");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("ix_auth_tokens_token");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_auth_tokens_user_id");

                    b.ToTable("auth_tokens", (string)null);
                });

            modelBuilder.Entity("AIATC.Domain.Models.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("avatar_url");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("email_verified");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("OAuthProvider")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("oauth_provider");

                    b.Property<string>("OAuthProviderId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("oauth_provider_id");

                    b.Property<string>("Roles")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("roles");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_users_is_active");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ix_users_username");

                    b.HasIndex("OAuthProvider", "OAuthProviderId")
                        .HasDatabaseName("ix_users_oauth");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("AIATC.Domain.Models.Users.AuthToken", b =>
                {
                    b.HasOne("AIATC.Domain.Models.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AIATC.Domain.Models.Users.User", b =>
                {
                    b.OwnsOne("AIATC.Domain.Models.Users.UserPreferences", "Preferences", b1 =>
                        {
                            b1.Property<Guid>("UserId");

                            b1.Property<bool>("EmailNotifications")
                                .HasJsonPropertyName("email_notifications");

                            b1.Property<int>("MasterVolume")
                                .HasJsonPropertyName("master_volume");

                            b1.Property<string>("PreferredAirport")
                                .HasJsonPropertyName("preferred_airport");

                            b1.Property<string>("PreferredDifficulty")
                                .IsRequired()
                                .HasJsonPropertyName("preferred_difficulty");

                            b1.Property<bool>("PublicStatistics")
                                .HasJsonPropertyName("public_statistics");

                            b1.Property<bool>("ShowTutorials")
                                .HasJsonPropertyName("show_tutorials");

                            b1.Property<bool>("TextToSpeechEnabled")
                                .HasJsonPropertyName("text_to_speech_enabled");

                            b1.Property<string>("Theme")
                                .IsRequired()
                                .HasJsonPropertyName("theme");

                            b1.Property<bool>("VoiceCommandsEnabled")
                                .HasJsonPropertyName("voice_commands_enabled");

                            b1.HasKey("UserId");

                            b1.ToTable("users");

                            b1
                                .ToJson("preferences")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("AIATC.Domain.Models.Users.UserStatistics", "Statistics", b1 =>
                        {
                            b1.Property<Guid>("UserId");

                            b1.Property<int>("AircraftLanded")
                                .HasJsonPropertyName("aircraft_landed");

                            b1.Property<int>("BestStreak")
                                .HasJsonPropertyName("best_streak");

                            b1.Property<int>("CurrentStreak")
                                .HasJsonPropertyName("current_streak");

                            b1.Property<int>("HighestScore")
                                .HasJsonPropertyName("highest_score");

                            b1.Property<int>("PerfectScenarios")
                                .HasJsonPropertyName("perfect_scenarios");

                            b1.Property<int>("ScenariosCompleted")
                                .HasJsonPropertyName("scenarios_completed");

                            b1.Property<int>("SkillRating")
                                .HasJsonPropertyName("skill_rating");

                            b1.Property<int>("TotalPlaytimeSeconds")
                                .HasJsonPropertyName("total_playtime_seconds");

                            b1.Property<int>("TotalViolations")
                                .HasJsonPropertyName("total_violations");

                            b1.HasKey("UserId");

                            b1.ToTable("users");

                            b1
                                .ToJson("statistics")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("Preferences")
                        .IsRequired();

                    b.Navigation("Statistics")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
