apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aiatc.fullname" . }}-usage-db
  labels:
    {{- include "aiatc.labels" . | nindent 4 }}
type: Opaque
stringData:
  connection-string: "Host={{ .Release.Name }}-postgresql;Port=5432;Database={{ .Values.postgresql.auth.database }};Username={{ .Values.postgresql.auth.username }};Password={{ .Values.postgresql.auth.password }}"
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aiatc.fullname" . }}-redis
  labels:
    {{- include "aiatc.labels" . | nindent 4 }}
type: Opaque
stringData:
  connection-string: "{{ .Release.Name }}-redis-master:6379"
---
{{- if .Values.externalReferenceDb.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.externalReferenceDb.passwordSecretName }}
  labels:
    {{- include "aiatc.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.externalReferenceDb.passwordSecretKey }}: {{ .Values.externalReferenceDb.passwordValue | quote }}
{{- end }}
